# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIDeepLearning.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_DeepLearningWindow(QDialog):
    def __init__(self):    # 构造方法
        super().__init__()    # 继承XX类的构造方法
        self.setupUi(self)    # 初始化本窗口

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1229, 742)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 551, 701))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(840, 370, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(820, 40, 161, 171))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.Button_Stop_2 = QtWidgets.QPushButton(self.splitter)
        self.Button_Stop_2.setObjectName("Button_Stop_2")
        self.Button_Stop = QtWidgets.QPushButton(self.splitter)
        self.Button_Stop.setObjectName("Button_Stop")
        self.Button_LoadModel = QtWidgets.QPushButton(self.splitter)
        self.Button_LoadModel.setObjectName("Button_LoadModel")
        self.Button_SaveModel = QtWidgets.QPushButton(self.splitter)
        self.Button_SaveModel.setObjectName("Button_SaveModel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1229, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "深度学习"))
        self.Button_Stop_2.setText(_translate("MainWindow", "开始训练"))
        self.Button_Stop.setText(_translate("MainWindow", "训练暂停"))
        self.Button_LoadModel.setText(_translate("MainWindow", "网络模型导入"))
        self.Button_SaveModel.setText(_translate("MainWindow", "网络模型保存"))
