# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1256, 793)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(1020, 0, 231, 781))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1021, 771))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Button_LoadData = QtWidgets.QPushButton(self.tab)
        self.Button_LoadData.setGeometry(QtCore.QRect(710, 320, 100, 50))
        self.Button_LoadData.setObjectName("Button_LoadData")
        self.Button_Recognize = QtWidgets.QPushButton(self.tab)
        self.Button_Recognize.setGeometry(QtCore.QRect(710, 410, 100, 50))
        self.Button_Recognize.setObjectName("Button_Recognize")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(260, 200, 54, 12))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Button_StopTrain = QtWidgets.QPushButton(self.tab_2)
        self.Button_StopTrain.setGeometry(QtCore.QRect(710, 226, 100, 50))
        self.Button_StopTrain.setObjectName("Button_StopTrain")
        self.Button_Train = QtWidgets.QPushButton(self.tab_2)
        self.Button_Train.setGeometry(QtCore.QRect(710, 122, 100, 50))
        self.Button_Train.setObjectName("Button_Train")
        self.Button_LoadModel = QtWidgets.QPushButton(self.tab_2)
        self.Button_LoadModel.setGeometry(QtCore.QRect(710, 174, 100, 50))
        self.Button_LoadModel.setObjectName("Button_LoadModel")
        self.Button_SaveModel = QtWidgets.QPushButton(self.tab_2)
        self.Button_SaveModel.setGeometry(QtCore.QRect(710, 278, 100, 50))
        self.Button_SaveModel.setObjectName("Button_SaveModel")
        self.Button_ReadModel = QtWidgets.QPushButton(self.tab_2)
        self.Button_ReadModel.setGeometry(QtCore.QRect(710, 330, 100, 50))
        self.Button_ReadModel.setObjectName("Button_ReadModel")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(280, 440, 511, 261))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_2, "")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于特征处理的手写数字识别"))
        self.Button_LoadData.setText(_translate("MainWindow", "导入数据集"))
        self.Button_Recognize.setText(_translate("MainWindow", "识别"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "基础功能"))
        self.Button_StopTrain.setText(_translate("MainWindow", "训练强制停止"))
        self.Button_Train.setText(_translate("MainWindow", "神经网络训练"))
        self.Button_LoadModel.setText(_translate("MainWindow", "网络模型导入"))
        self.Button_SaveModel.setText(_translate("MainWindow", "模型保存"))
        self.Button_ReadModel.setText(_translate("MainWindow", "模型读取"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "神经网络"))
